### ISSUE TITLE
publish to crates.io

### ISSUE THREAD

**Issue by robin-thoene** [cordx56/rustowl#19]
As an additional installation option, installing the required rust bin from crates.io like other binaries would be nice and convenient.

**Comment by IwantHAPPINESS** [comment]
that would be nice

**Comment by gerard-ryan-immersaview** [comment]
It might still make sense from the perspective of registering the crate name in case someone else takes it.  
Besides the `install.sh` could still exist and be the supported way for installing.  
It might make maintaining the `install.sh` a little easier too as it wouldn't need curl and the version could just be locked via crates.io instead of updating the script every release.

**Comment by cordx56** [comment]
@gerard-ryan-immersaview Thank you for your opinion!  

I have published RustOwl to crates.io: https://crates.io/crates/rustowl.  
Additionally, I updated the installation manual to use `cargo install` with `rustup`.  

We plan to remove `install.sh` in the future.

**Comment by robin-thoene** [comment]
Awesome!

**Comment by robin-thoene** [comment]
I just tried it:

I first installed the required toolchain

```
rustup toolchain install nightly-2025-02-22
```

and then used the new documented install command

```
rustup run nightly-2025-02-22 cargo install rustowl
```

However, I receive some errors like this for several crates

![Image](https://github.com/user-attachments/assets/26997c50-b2fe-4dfe-a961-97a724249e78)

After adding the suggested components, the error still remains.

I am using an Arch Linux based distro, but also fired up my MacBook (Sequoia 15.2) and was able to reproduce the same.

**Comment by cordx56** [comment]
Hmm, maybe your environment lacks some components .
This may be avoided by using `install.sh` since it specify required components.

This cannot be done by one-liner command.
So I fix document to use `install.sh`.
