### ISSUE TITLE
VSCode RustOwl Always checking

### ISSUE THREAD

**Issue by G-M0N3Y-2503** [cordx56/rustowl#75]
### Bug Description

This may be a couple of bugs in one, but the core of the issue is triggered by the following steps:
1. Open a Rust project
2. Wait for rust-analyzer and rustowl to finish their checks
3. Add a space to the end of a comment.
4. Repeat step `3` periodically

This results in the following symptoms:
1. The rustowl status will always be stuck checking. 
     ![Many rustowl "checking" notifications](https://github.com/user-attachments/assets/53018039-d9e1-4722-8b66-c8e74d04afeb)
3. `rustowlc` is effectively always running when typing/making changes, using a lot of CPU.

A holistic fix would be to:
1. Debounce triggers, especially since the result takes some time to show anyway.
2. Only run when the cursor is placed on reasonable Rust syntax, i.e the middle of a variable.

### Environment

- rustowl v0.2.0
- rustup 1.28.1
- rustc 1.86.0
- VSCode 1.99.2
- OS: Manjaro Linux

**Comment by cordx56** [comment]
Thank you for using RustOwl.

Currently, in the Unix-like systems, VS Code shows multiple loading progress but the analyzing process is only one and old one is killed when the source code is changed.
The analysis runs on saving any source code in the workspace.

We released v0.2.1 and it contain improvement for showing progress.
So please try new version.

**Comment by G-M0N3Y-2503** [comment]
The rustowlc process is behaving as you say, but the notifications in VS Code are not being cleaned up, so this looks like just a UI issue.

**Comment by cordx56** [comment]
I confirmed that the problem is fixed before v0.3.0. Did you try v0.3.0?

**Comment by G-M0N3Y-2503** [comment]
Hmm it's still happening for me with https://github.com/G-M0N3Y-2503/current_dir

![Image](https://github.com/user-attachments/assets/a67ebcfc-d609-484c-a459-293fc7d2f135)

**Comment by avifenesh** [comment]
@G-M0N3Y-2503 can you please provide additional information so it's possible to check and reproduce your case? What host, tool chain, etc.?
